/**
 * SellAuth
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Coupon model module.
 * @module model/Coupon
 * @version 1.0.0
 */
class Coupon {
    /**
     * Constructs a new <code>Coupon</code>.
     * @alias module:model/Coupon
     */
    constructor() { 
        
        Coupon.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Coupon</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Coupon} obj Optional instance to populate.
     * @return {module:model/Coupon} The populated <code>Coupon</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Coupon();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'String');
            }
            if (data.hasOwnProperty('salt')) {
                obj['salt'] = ApiClient.convertToType(data['salt'], 'String');
            }
            if (data.hasOwnProperty('global')) {
                obj['global'] = ApiClient.convertToType(data['global'], 'Number');
            }
            if (data.hasOwnProperty('discount')) {
                obj['discount'] = ApiClient.convertToType(data['discount'], 'Number');
            }
            if (data.hasOwnProperty('uses')) {
                obj['uses'] = ApiClient.convertToType(data['uses'], 'Number');
            }
            if (data.hasOwnProperty('max_uses')) {
                obj['max_uses'] = ApiClient.convertToType(data['max_uses'], 'Number');
            }
            if (data.hasOwnProperty('allowed_emails')) {
                obj['allowed_emails'] = ApiClient.convertToType(data['allowed_emails'], ['String']);
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('expiration_date')) {
                obj['expiration_date'] = ApiClient.convertToType(data['expiration_date'], 'Date');
            }
            if (data.hasOwnProperty('shop_id')) {
                obj['shop_id'] = ApiClient.convertToType(data['shop_id'], 'Number');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Coupon</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Coupon</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['code'] && !(typeof data['code'] === 'string' || data['code'] instanceof String)) {
            throw new Error("Expected the field `code` to be a primitive type in the JSON string but got " + data['code']);
        }
        // ensure the json data is a string
        if (data['salt'] && !(typeof data['salt'] === 'string' || data['salt'] instanceof String)) {
            throw new Error("Expected the field `salt` to be a primitive type in the JSON string but got " + data['salt']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['allowed_emails'])) {
            throw new Error("Expected the field `allowed_emails` to be an array in the JSON data but got " + data['allowed_emails']);
        }
        // ensure the json data is a string
        if (data['type'] && !(typeof data['type'] === 'string' || data['type'] instanceof String)) {
            throw new Error("Expected the field `type` to be a primitive type in the JSON string but got " + data['type']);
        }

        return true;
    }


}



/**
 * @member {Number} id
 */
Coupon.prototype['id'] = undefined;

/**
 * @member {String} code
 */
Coupon.prototype['code'] = undefined;

/**
 * @member {String} salt
 */
Coupon.prototype['salt'] = undefined;

/**
 * @member {Number} global
 */
Coupon.prototype['global'] = undefined;

/**
 * @member {Number} discount
 */
Coupon.prototype['discount'] = undefined;

/**
 * @member {Number} uses
 */
Coupon.prototype['uses'] = undefined;

/**
 * @member {Number} max_uses
 */
Coupon.prototype['max_uses'] = undefined;

/**
 * @member {Array.<String>} allowed_emails
 */
Coupon.prototype['allowed_emails'] = undefined;

/**
 * @member {String} type
 */
Coupon.prototype['type'] = undefined;

/**
 * @member {Date} expiration_date
 */
Coupon.prototype['expiration_date'] = undefined;

/**
 * @member {Number} shop_id
 */
Coupon.prototype['shop_id'] = undefined;

/**
 * @member {Date} created_at
 */
Coupon.prototype['created_at'] = undefined;

/**
 * @member {Date} updated_at
 */
Coupon.prototype['updated_at'] = undefined;






export default Coupon;

