/**
 * SellAuth
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GetV1ShopsShopIdProducts200ResponseDataInnerGroup from './GetV1ShopsShopIdProducts200ResponseDataInnerGroup';

/**
 * The GetV1ShopsShopIdProducts200ResponseDataInner model module.
 * @module model/GetV1ShopsShopIdProducts200ResponseDataInner
 * @version 1.0.0
 */
class GetV1ShopsShopIdProducts200ResponseDataInner {
    /**
     * Constructs a new <code>GetV1ShopsShopIdProducts200ResponseDataInner</code>.
     * @alias module:model/GetV1ShopsShopIdProducts200ResponseDataInner
     */
    constructor() { 
        
        GetV1ShopsShopIdProducts200ResponseDataInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetV1ShopsShopIdProducts200ResponseDataInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetV1ShopsShopIdProducts200ResponseDataInner} obj Optional instance to populate.
     * @return {module:model/GetV1ShopsShopIdProducts200ResponseDataInner} The populated <code>GetV1ShopsShopIdProducts200ResponseDataInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetV1ShopsShopIdProducts200ResponseDataInner();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('salt')) {
                obj['salt'] = ApiClient.convertToType(data['salt'], 'String');
            }
            if (data.hasOwnProperty('path')) {
                obj['path'] = ApiClient.convertToType(data['path'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('price')) {
                obj['price'] = ApiClient.convertToType(data['price'], 'String');
            }
            if (data.hasOwnProperty('currency')) {
                obj['currency'] = ApiClient.convertToType(data['currency'], 'String');
            }
            if (data.hasOwnProperty('deliverables_type')) {
                obj['deliverables_type'] = ApiClient.convertToType(data['deliverables_type'], 'String');
            }
            if (data.hasOwnProperty('stock')) {
                obj['stock'] = ApiClient.convertToType(data['stock'], 'Number');
            }
            if (data.hasOwnProperty('group_id')) {
                obj['group_id'] = ApiClient.convertToType(data['group_id'], 'Number');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('visibility')) {
                obj['visibility'] = ApiClient.convertToType(data['visibility'], 'String');
            }
            if (data.hasOwnProperty('stock_count')) {
                obj['stock_count'] = ApiClient.convertToType(data['stock_count'], 'Number');
            }
            if (data.hasOwnProperty('group')) {
                obj['group'] = GetV1ShopsShopIdProducts200ResponseDataInnerGroup.constructFromObject(data['group']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GetV1ShopsShopIdProducts200ResponseDataInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GetV1ShopsShopIdProducts200ResponseDataInner</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['salt'] && !(typeof data['salt'] === 'string' || data['salt'] instanceof String)) {
            throw new Error("Expected the field `salt` to be a primitive type in the JSON string but got " + data['salt']);
        }
        // ensure the json data is a string
        if (data['path'] && !(typeof data['path'] === 'string' || data['path'] instanceof String)) {
            throw new Error("Expected the field `path` to be a primitive type in the JSON string but got " + data['path']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['price'] && !(typeof data['price'] === 'string' || data['price'] instanceof String)) {
            throw new Error("Expected the field `price` to be a primitive type in the JSON string but got " + data['price']);
        }
        // ensure the json data is a string
        if (data['currency'] && !(typeof data['currency'] === 'string' || data['currency'] instanceof String)) {
            throw new Error("Expected the field `currency` to be a primitive type in the JSON string but got " + data['currency']);
        }
        // ensure the json data is a string
        if (data['deliverables_type'] && !(typeof data['deliverables_type'] === 'string' || data['deliverables_type'] instanceof String)) {
            throw new Error("Expected the field `deliverables_type` to be a primitive type in the JSON string but got " + data['deliverables_type']);
        }
        // ensure the json data is a string
        if (data['type'] && !(typeof data['type'] === 'string' || data['type'] instanceof String)) {
            throw new Error("Expected the field `type` to be a primitive type in the JSON string but got " + data['type']);
        }
        // ensure the json data is a string
        if (data['visibility'] && !(typeof data['visibility'] === 'string' || data['visibility'] instanceof String)) {
            throw new Error("Expected the field `visibility` to be a primitive type in the JSON string but got " + data['visibility']);
        }
        // validate the optional field `group`
        if (data['group']) { // data not null
          GetV1ShopsShopIdProducts200ResponseDataInnerGroup.validateJSON(data['group']);
        }

        return true;
    }


}



/**
 * @member {Number} id
 */
GetV1ShopsShopIdProducts200ResponseDataInner.prototype['id'] = undefined;

/**
 * @member {String} salt
 */
GetV1ShopsShopIdProducts200ResponseDataInner.prototype['salt'] = undefined;

/**
 * @member {String} path
 */
GetV1ShopsShopIdProducts200ResponseDataInner.prototype['path'] = undefined;

/**
 * @member {String} name
 */
GetV1ShopsShopIdProducts200ResponseDataInner.prototype['name'] = undefined;

/**
 * @member {String} price
 */
GetV1ShopsShopIdProducts200ResponseDataInner.prototype['price'] = undefined;

/**
 * @member {String} currency
 */
GetV1ShopsShopIdProducts200ResponseDataInner.prototype['currency'] = undefined;

/**
 * @member {String} deliverables_type
 */
GetV1ShopsShopIdProducts200ResponseDataInner.prototype['deliverables_type'] = undefined;

/**
 * @member {Number} stock
 */
GetV1ShopsShopIdProducts200ResponseDataInner.prototype['stock'] = undefined;

/**
 * @member {Number} group_id
 */
GetV1ShopsShopIdProducts200ResponseDataInner.prototype['group_id'] = undefined;

/**
 * @member {String} type
 */
GetV1ShopsShopIdProducts200ResponseDataInner.prototype['type'] = undefined;

/**
 * @member {String} visibility
 */
GetV1ShopsShopIdProducts200ResponseDataInner.prototype['visibility'] = undefined;

/**
 * @member {Number} stock_count
 */
GetV1ShopsShopIdProducts200ResponseDataInner.prototype['stock_count'] = undefined;

/**
 * @member {module:model/GetV1ShopsShopIdProducts200ResponseDataInnerGroup} group
 */
GetV1ShopsShopIdProducts200ResponseDataInner.prototype['group'] = undefined;






export default GetV1ShopsShopIdProducts200ResponseDataInner;

