/**
 * SellAuth
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BlacklistEntry from './BlacklistEntry';

/**
 * The GetV1ShopsShopIdBlacklist200ResponseDataInner model module.
 * @module model/GetV1ShopsShopIdBlacklist200ResponseDataInner
 * @version 1.0.0
 */
class GetV1ShopsShopIdBlacklist200ResponseDataInner {
    /**
     * Constructs a new <code>GetV1ShopsShopIdBlacklist200ResponseDataInner</code>.
     * @alias module:model/GetV1ShopsShopIdBlacklist200ResponseDataInner
     * @implements module:model/BlacklistEntry
     */
    constructor() { 
        BlacklistEntry.initialize(this);
        GetV1ShopsShopIdBlacklist200ResponseDataInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetV1ShopsShopIdBlacklist200ResponseDataInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetV1ShopsShopIdBlacklist200ResponseDataInner} obj Optional instance to populate.
     * @return {module:model/GetV1ShopsShopIdBlacklist200ResponseDataInner} The populated <code>GetV1ShopsShopIdBlacklist200ResponseDataInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetV1ShopsShopIdBlacklist200ResponseDataInner();
            BlacklistEntry.constructFromObject(data, obj);

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('shop_id')) {
                obj['shop_id'] = ApiClient.convertToType(data['shop_id'], 'Number');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'String');
            }
            if (data.hasOwnProperty('reason')) {
                obj['reason'] = ApiClient.convertToType(data['reason'], 'String');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'Date');
            }
            if (data.hasOwnProperty('deleted_at')) {
                obj['deleted_at'] = ApiClient.convertToType(data['deleted_at'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GetV1ShopsShopIdBlacklist200ResponseDataInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GetV1ShopsShopIdBlacklist200ResponseDataInner</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['type'] && !(typeof data['type'] === 'string' || data['type'] instanceof String)) {
            throw new Error("Expected the field `type` to be a primitive type in the JSON string but got " + data['type']);
        }
        // ensure the json data is a string
        if (data['value'] && !(typeof data['value'] === 'string' || data['value'] instanceof String)) {
            throw new Error("Expected the field `value` to be a primitive type in the JSON string but got " + data['value']);
        }
        // ensure the json data is a string
        if (data['reason'] && !(typeof data['reason'] === 'string' || data['reason'] instanceof String)) {
            throw new Error("Expected the field `reason` to be a primitive type in the JSON string but got " + data['reason']);
        }
        // ensure the json data is a string
        if (data['deleted_at'] && !(typeof data['deleted_at'] === 'string' || data['deleted_at'] instanceof String)) {
            throw new Error("Expected the field `deleted_at` to be a primitive type in the JSON string but got " + data['deleted_at']);
        }

        return true;
    }


}



/**
 * @member {Number} id
 */
GetV1ShopsShopIdBlacklist200ResponseDataInner.prototype['id'] = undefined;

/**
 * @member {Number} shop_id
 */
GetV1ShopsShopIdBlacklist200ResponseDataInner.prototype['shop_id'] = undefined;

/**
 * @member {String} type
 */
GetV1ShopsShopIdBlacklist200ResponseDataInner.prototype['type'] = undefined;

/**
 * @member {String} value
 */
GetV1ShopsShopIdBlacklist200ResponseDataInner.prototype['value'] = undefined;

/**
 * @member {String} reason
 */
GetV1ShopsShopIdBlacklist200ResponseDataInner.prototype['reason'] = undefined;

/**
 * @member {Date} created_at
 */
GetV1ShopsShopIdBlacklist200ResponseDataInner.prototype['created_at'] = undefined;

/**
 * @member {Date} updated_at
 */
GetV1ShopsShopIdBlacklist200ResponseDataInner.prototype['updated_at'] = undefined;

/**
 * @member {String} deleted_at
 */
GetV1ShopsShopIdBlacklist200ResponseDataInner.prototype['deleted_at'] = undefined;


// Implement BlacklistEntry interface:
/**
 * @member {Number} id
 */
BlacklistEntry.prototype['id'] = undefined;
/**
 * @member {Number} shop_id
 */
BlacklistEntry.prototype['shop_id'] = undefined;
/**
 * @member {String} type
 */
BlacklistEntry.prototype['type'] = undefined;
/**
 * @member {String} value
 */
BlacklistEntry.prototype['value'] = undefined;
/**
 * @member {String} reason
 */
BlacklistEntry.prototype['reason'] = undefined;
/**
 * @member {Date} created_at
 */
BlacklistEntry.prototype['created_at'] = undefined;
/**
 * @member {Date} updated_at
 */
BlacklistEntry.prototype['updated_at'] = undefined;




export default GetV1ShopsShopIdBlacklist200ResponseDataInner;

