/**
 * SellAuth
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CustomField from './CustomField';
import PostV1ShopsShopIdProducts200ResponseAllOfCustomFieldsInnerAllOfPivot from './PostV1ShopsShopIdProducts200ResponseAllOfCustomFieldsInnerAllOfPivot';

/**
 * The PostV1ShopsShopIdProducts200ResponseAllOfCustomFieldsInner model module.
 * @module model/PostV1ShopsShopIdProducts200ResponseAllOfCustomFieldsInner
 * @version 1.0.0
 */
class PostV1ShopsShopIdProducts200ResponseAllOfCustomFieldsInner {
    /**
     * Constructs a new <code>PostV1ShopsShopIdProducts200ResponseAllOfCustomFieldsInner</code>.
     * @alias module:model/PostV1ShopsShopIdProducts200ResponseAllOfCustomFieldsInner
     * @implements module:model/CustomField
     */
    constructor() { 
        CustomField.initialize(this);
        PostV1ShopsShopIdProducts200ResponseAllOfCustomFieldsInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PostV1ShopsShopIdProducts200ResponseAllOfCustomFieldsInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PostV1ShopsShopIdProducts200ResponseAllOfCustomFieldsInner} obj Optional instance to populate.
     * @return {module:model/PostV1ShopsShopIdProducts200ResponseAllOfCustomFieldsInner} The populated <code>PostV1ShopsShopIdProducts200ResponseAllOfCustomFieldsInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PostV1ShopsShopIdProducts200ResponseAllOfCustomFieldsInner();
            CustomField.constructFromObject(data, obj);

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('shop_id')) {
                obj['shop_id'] = ApiClient.convertToType(data['shop_id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('hint')) {
                obj['hint'] = ApiClient.convertToType(data['hint'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('options')) {
                obj['options'] = ApiClient.convertToType(data['options'], 'String');
            }
            if (data.hasOwnProperty('is_required')) {
                obj['is_required'] = ApiClient.convertToType(data['is_required'], 'Boolean');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'Date');
            }
            if (data.hasOwnProperty('pivot')) {
                obj['pivot'] = PostV1ShopsShopIdProducts200ResponseAllOfCustomFieldsInnerAllOfPivot.constructFromObject(data['pivot']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PostV1ShopsShopIdProducts200ResponseAllOfCustomFieldsInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PostV1ShopsShopIdProducts200ResponseAllOfCustomFieldsInner</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['hint'] && !(typeof data['hint'] === 'string' || data['hint'] instanceof String)) {
            throw new Error("Expected the field `hint` to be a primitive type in the JSON string but got " + data['hint']);
        }
        // ensure the json data is a string
        if (data['type'] && !(typeof data['type'] === 'string' || data['type'] instanceof String)) {
            throw new Error("Expected the field `type` to be a primitive type in the JSON string but got " + data['type']);
        }
        // ensure the json data is a string
        if (data['options'] && !(typeof data['options'] === 'string' || data['options'] instanceof String)) {
            throw new Error("Expected the field `options` to be a primitive type in the JSON string but got " + data['options']);
        }
        // validate the optional field `pivot`
        if (data['pivot']) { // data not null
          PostV1ShopsShopIdProducts200ResponseAllOfCustomFieldsInnerAllOfPivot.validateJSON(data['pivot']);
        }

        return true;
    }


}



/**
 * @member {Number} id
 */
PostV1ShopsShopIdProducts200ResponseAllOfCustomFieldsInner.prototype['id'] = undefined;

/**
 * @member {Number} shop_id
 */
PostV1ShopsShopIdProducts200ResponseAllOfCustomFieldsInner.prototype['shop_id'] = undefined;

/**
 * @member {String} name
 */
PostV1ShopsShopIdProducts200ResponseAllOfCustomFieldsInner.prototype['name'] = undefined;

/**
 * @member {String} hint
 */
PostV1ShopsShopIdProducts200ResponseAllOfCustomFieldsInner.prototype['hint'] = undefined;

/**
 * @member {String} type
 */
PostV1ShopsShopIdProducts200ResponseAllOfCustomFieldsInner.prototype['type'] = undefined;

/**
 * @member {String} options
 */
PostV1ShopsShopIdProducts200ResponseAllOfCustomFieldsInner.prototype['options'] = undefined;

/**
 * @member {Boolean} is_required
 */
PostV1ShopsShopIdProducts200ResponseAllOfCustomFieldsInner.prototype['is_required'] = undefined;

/**
 * @member {Date} created_at
 */
PostV1ShopsShopIdProducts200ResponseAllOfCustomFieldsInner.prototype['created_at'] = undefined;

/**
 * @member {Date} updated_at
 */
PostV1ShopsShopIdProducts200ResponseAllOfCustomFieldsInner.prototype['updated_at'] = undefined;

/**
 * @member {module:model/PostV1ShopsShopIdProducts200ResponseAllOfCustomFieldsInnerAllOfPivot} pivot
 */
PostV1ShopsShopIdProducts200ResponseAllOfCustomFieldsInner.prototype['pivot'] = undefined;


// Implement CustomField interface:
/**
 * @member {Number} id
 */
CustomField.prototype['id'] = undefined;
/**
 * @member {Number} shop_id
 */
CustomField.prototype['shop_id'] = undefined;
/**
 * @member {String} name
 */
CustomField.prototype['name'] = undefined;
/**
 * @member {String} hint
 */
CustomField.prototype['hint'] = undefined;
/**
 * @member {String} type
 */
CustomField.prototype['type'] = undefined;
/**
 * @member {String} options
 */
CustomField.prototype['options'] = undefined;
/**
 * @member {Boolean} is_required
 */
CustomField.prototype['is_required'] = undefined;
/**
 * @member {Date} created_at
 */
CustomField.prototype['created_at'] = undefined;
/**
 * @member {Date} updated_at
 */
CustomField.prototype['updated_at'] = undefined;




export default PostV1ShopsShopIdProducts200ResponseAllOfCustomFieldsInner;

