/**
 * SellAuth
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PostV1ShopsShopIdPayoutsPayoutRequest model module.
 * @module model/PostV1ShopsShopIdPayoutsPayoutRequest
 * @version 1.0.0
 */
class PostV1ShopsShopIdPayoutsPayoutRequest {
    /**
     * Constructs a new <code>PostV1ShopsShopIdPayoutsPayoutRequest</code>.
     * @alias module:model/PostV1ShopsShopIdPayoutsPayoutRequest
     * @param currency {module:model/PostV1ShopsShopIdPayoutsPayoutRequest.CurrencyEnum} 
     * @param address {String} 
     * @param amount {Number} 
     */
    constructor(currency, address, amount) { 
        
        PostV1ShopsShopIdPayoutsPayoutRequest.initialize(this, currency, address, amount);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, currency, address, amount) { 
        obj['currency'] = currency;
        obj['address'] = address;
        obj['amount'] = amount;
    }

    /**
     * Constructs a <code>PostV1ShopsShopIdPayoutsPayoutRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PostV1ShopsShopIdPayoutsPayoutRequest} obj Optional instance to populate.
     * @return {module:model/PostV1ShopsShopIdPayoutsPayoutRequest} The populated <code>PostV1ShopsShopIdPayoutsPayoutRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PostV1ShopsShopIdPayoutsPayoutRequest();

            if (data.hasOwnProperty('currency')) {
                obj['currency'] = ApiClient.convertToType(data['currency'], 'String');
            }
            if (data.hasOwnProperty('address')) {
                obj['address'] = ApiClient.convertToType(data['address'], 'String');
            }
            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PostV1ShopsShopIdPayoutsPayoutRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PostV1ShopsShopIdPayoutsPayoutRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PostV1ShopsShopIdPayoutsPayoutRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['currency'] && !(typeof data['currency'] === 'string' || data['currency'] instanceof String)) {
            throw new Error("Expected the field `currency` to be a primitive type in the JSON string but got " + data['currency']);
        }
        // ensure the json data is a string
        if (data['address'] && !(typeof data['address'] === 'string' || data['address'] instanceof String)) {
            throw new Error("Expected the field `address` to be a primitive type in the JSON string but got " + data['address']);
        }

        return true;
    }


}

PostV1ShopsShopIdPayoutsPayoutRequest.RequiredProperties = ["currency", "address", "amount"];

/**
 * 
 * @member {module:model/PostV1ShopsShopIdPayoutsPayoutRequest.CurrencyEnum} currency
 */
PostV1ShopsShopIdPayoutsPayoutRequest.prototype['currency'] = undefined;

/**
 * 
 * @member {String} address
 */
PostV1ShopsShopIdPayoutsPayoutRequest.prototype['address'] = undefined;

/**
 * 
 * @member {Number} amount
 */
PostV1ShopsShopIdPayoutsPayoutRequest.prototype['amount'] = undefined;





/**
 * Allowed values for the <code>currency</code> property.
 * @enum {String}
 * @readonly
 */
PostV1ShopsShopIdPayoutsPayoutRequest['CurrencyEnum'] = {

    /**
     * value: "btc"
     * @const
     */
    "btc": "btc",

    /**
     * value: "ltc"
     * @const
     */
    "ltc": "ltc"
};



export default PostV1ShopsShopIdPayoutsPayoutRequest;

