/**
 * SellAuth
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PostV1ShopsShopIdProducts200ResponseAllOfCustomFieldsInnerAllOfPivot model module.
 * @module model/PostV1ShopsShopIdProducts200ResponseAllOfCustomFieldsInnerAllOfPivot
 * @version 1.0.0
 */
class PostV1ShopsShopIdProducts200ResponseAllOfCustomFieldsInnerAllOfPivot {
    /**
     * Constructs a new <code>PostV1ShopsShopIdProducts200ResponseAllOfCustomFieldsInnerAllOfPivot</code>.
     * @alias module:model/PostV1ShopsShopIdProducts200ResponseAllOfCustomFieldsInnerAllOfPivot
     */
    constructor() { 
        
        PostV1ShopsShopIdProducts200ResponseAllOfCustomFieldsInnerAllOfPivot.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PostV1ShopsShopIdProducts200ResponseAllOfCustomFieldsInnerAllOfPivot</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PostV1ShopsShopIdProducts200ResponseAllOfCustomFieldsInnerAllOfPivot} obj Optional instance to populate.
     * @return {module:model/PostV1ShopsShopIdProducts200ResponseAllOfCustomFieldsInnerAllOfPivot} The populated <code>PostV1ShopsShopIdProducts200ResponseAllOfCustomFieldsInnerAllOfPivot</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PostV1ShopsShopIdProducts200ResponseAllOfCustomFieldsInnerAllOfPivot();

            if (data.hasOwnProperty('morphable_id')) {
                obj['morphable_id'] = ApiClient.convertToType(data['morphable_id'], 'Number');
            }
            if (data.hasOwnProperty('custom_field_id')) {
                obj['custom_field_id'] = ApiClient.convertToType(data['custom_field_id'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PostV1ShopsShopIdProducts200ResponseAllOfCustomFieldsInnerAllOfPivot</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PostV1ShopsShopIdProducts200ResponseAllOfCustomFieldsInnerAllOfPivot</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Number} morphable_id
 */
PostV1ShopsShopIdProducts200ResponseAllOfCustomFieldsInnerAllOfPivot.prototype['morphable_id'] = undefined;

/**
 * @member {Number} custom_field_id
 */
PostV1ShopsShopIdProducts200ResponseAllOfCustomFieldsInnerAllOfPivot.prototype['custom_field_id'] = undefined;






export default PostV1ShopsShopIdProducts200ResponseAllOfCustomFieldsInnerAllOfPivot;

