/**
 * SellAuth
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PostV1ShopsShopIdGroupsRequest model module.
 * @module model/PostV1ShopsShopIdGroupsRequest
 * @version 1.0.0
 */
class PostV1ShopsShopIdGroupsRequest {
    /**
     * Constructs a new <code>PostV1ShopsShopIdGroupsRequest</code>.
     * @alias module:model/PostV1ShopsShopIdGroupsRequest
     * @param name {String} 
     * @param visibility {module:model/PostV1ShopsShopIdGroupsRequest.VisibilityEnum} 
     */
    constructor(name, visibility) { 
        
        PostV1ShopsShopIdGroupsRequest.initialize(this, name, visibility);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, visibility) { 
        obj['name'] = name;
        obj['visibility'] = visibility;
    }

    /**
     * Constructs a <code>PostV1ShopsShopIdGroupsRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PostV1ShopsShopIdGroupsRequest} obj Optional instance to populate.
     * @return {module:model/PostV1ShopsShopIdGroupsRequest} The populated <code>PostV1ShopsShopIdGroupsRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PostV1ShopsShopIdGroupsRequest();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('image_id')) {
                obj['image_id'] = ApiClient.convertToType(data['image_id'], 'String');
            }
            if (data.hasOwnProperty('visibility')) {
                obj['visibility'] = ApiClient.convertToType(data['visibility'], 'String');
            }
            if (data.hasOwnProperty('products')) {
                obj['products'] = ApiClient.convertToType(data['products'], Object);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PostV1ShopsShopIdGroupsRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PostV1ShopsShopIdGroupsRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PostV1ShopsShopIdGroupsRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['image_id'] && !(typeof data['image_id'] === 'string' || data['image_id'] instanceof String)) {
            throw new Error("Expected the field `image_id` to be a primitive type in the JSON string but got " + data['image_id']);
        }
        // ensure the json data is a string
        if (data['visibility'] && !(typeof data['visibility'] === 'string' || data['visibility'] instanceof String)) {
            throw new Error("Expected the field `visibility` to be a primitive type in the JSON string but got " + data['visibility']);
        }

        return true;
    }


}

PostV1ShopsShopIdGroupsRequest.RequiredProperties = ["name", "visibility"];

/**
 * 
 * @member {String} name
 */
PostV1ShopsShopIdGroupsRequest.prototype['name'] = undefined;

/**
 * 
 * @member {String} image_id
 */
PostV1ShopsShopIdGroupsRequest.prototype['image_id'] = undefined;

/**
 * 
 * @member {module:model/PostV1ShopsShopIdGroupsRequest.VisibilityEnum} visibility
 */
PostV1ShopsShopIdGroupsRequest.prototype['visibility'] = undefined;

/**
 * 
 * @member {Object} products
 */
PostV1ShopsShopIdGroupsRequest.prototype['products'] = undefined;





/**
 * Allowed values for the <code>visibility</code> property.
 * @enum {String}
 * @readonly
 */
PostV1ShopsShopIdGroupsRequest['VisibilityEnum'] = {

    /**
     * value: "public"
     * @const
     */
    "public": "public",

    /**
     * value: "unlisted"
     * @const
     */
    "unlisted": "unlisted",

    /**
     * value: "private"
     * @const
     */
    "private": "private"
};



export default PostV1ShopsShopIdGroupsRequest;

