/**
 * SellAuth
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PutV1ShopsShopIdCustomFieldsCustomFieldIdRequest model module.
 * @module model/PutV1ShopsShopIdCustomFieldsCustomFieldIdRequest
 * @version 1.0.0
 */
class PutV1ShopsShopIdCustomFieldsCustomFieldIdRequest {
    /**
     * Constructs a new <code>PutV1ShopsShopIdCustomFieldsCustomFieldIdRequest</code>.
     * @alias module:model/PutV1ShopsShopIdCustomFieldsCustomFieldIdRequest
     * @param name {String} 
     * @param type {String} 
     */
    constructor(name, type) { 
        
        PutV1ShopsShopIdCustomFieldsCustomFieldIdRequest.initialize(this, name, type);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, type) { 
        obj['name'] = name;
        obj['type'] = type;
    }

    /**
     * Constructs a <code>PutV1ShopsShopIdCustomFieldsCustomFieldIdRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PutV1ShopsShopIdCustomFieldsCustomFieldIdRequest} obj Optional instance to populate.
     * @return {module:model/PutV1ShopsShopIdCustomFieldsCustomFieldIdRequest} The populated <code>PutV1ShopsShopIdCustomFieldsCustomFieldIdRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PutV1ShopsShopIdCustomFieldsCustomFieldIdRequest();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('hint')) {
                obj['hint'] = ApiClient.convertToType(data['hint'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('options')) {
                obj['options'] = ApiClient.convertToType(data['options'], 'String');
            }
            if (data.hasOwnProperty('is_required')) {
                obj['is_required'] = ApiClient.convertToType(data['is_required'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PutV1ShopsShopIdCustomFieldsCustomFieldIdRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PutV1ShopsShopIdCustomFieldsCustomFieldIdRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PutV1ShopsShopIdCustomFieldsCustomFieldIdRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['hint'] && !(typeof data['hint'] === 'string' || data['hint'] instanceof String)) {
            throw new Error("Expected the field `hint` to be a primitive type in the JSON string but got " + data['hint']);
        }
        // ensure the json data is a string
        if (data['type'] && !(typeof data['type'] === 'string' || data['type'] instanceof String)) {
            throw new Error("Expected the field `type` to be a primitive type in the JSON string but got " + data['type']);
        }
        // ensure the json data is a string
        if (data['options'] && !(typeof data['options'] === 'string' || data['options'] instanceof String)) {
            throw new Error("Expected the field `options` to be a primitive type in the JSON string but got " + data['options']);
        }

        return true;
    }


}

PutV1ShopsShopIdCustomFieldsCustomFieldIdRequest.RequiredProperties = ["name", "type"];

/**
 * 
 * @member {String} name
 */
PutV1ShopsShopIdCustomFieldsCustomFieldIdRequest.prototype['name'] = undefined;

/**
 * 
 * @member {String} hint
 */
PutV1ShopsShopIdCustomFieldsCustomFieldIdRequest.prototype['hint'] = undefined;

/**
 * 
 * @member {String} type
 */
PutV1ShopsShopIdCustomFieldsCustomFieldIdRequest.prototype['type'] = undefined;

/**
 * 
 * @member {String} options
 */
PutV1ShopsShopIdCustomFieldsCustomFieldIdRequest.prototype['options'] = undefined;

/**
 * 
 * @member {Boolean} is_required
 */
PutV1ShopsShopIdCustomFieldsCustomFieldIdRequest.prototype['is_required'] = undefined;






export default PutV1ShopsShopIdCustomFieldsCustomFieldIdRequest;

