/**
 * SellAuth
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PutV1ShopsShopIdCouponsCouponIdUpdateRequest model module.
 * @module model/PutV1ShopsShopIdCouponsCouponIdUpdateRequest
 * @version 1.0.0
 */
class PutV1ShopsShopIdCouponsCouponIdUpdateRequest {
    /**
     * Constructs a new <code>PutV1ShopsShopIdCouponsCouponIdUpdateRequest</code>.
     * @alias module:model/PutV1ShopsShopIdCouponsCouponIdUpdateRequest
     * @param code {String} 
     * @param global {Boolean} 
     * @param discount {Number} 
     * @param type {module:model/PutV1ShopsShopIdCouponsCouponIdUpdateRequest.TypeEnum} 
     */
    constructor(code, global, discount, type) { 
        
        PutV1ShopsShopIdCouponsCouponIdUpdateRequest.initialize(this, code, global, discount, type);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, code, global, discount, type) { 
        obj['code'] = code;
        obj['global'] = global;
        obj['discount'] = discount;
        obj['type'] = type;
    }

    /**
     * Constructs a <code>PutV1ShopsShopIdCouponsCouponIdUpdateRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PutV1ShopsShopIdCouponsCouponIdUpdateRequest} obj Optional instance to populate.
     * @return {module:model/PutV1ShopsShopIdCouponsCouponIdUpdateRequest} The populated <code>PutV1ShopsShopIdCouponsCouponIdUpdateRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PutV1ShopsShopIdCouponsCouponIdUpdateRequest();

            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'String');
            }
            if (data.hasOwnProperty('global')) {
                obj['global'] = ApiClient.convertToType(data['global'], 'Boolean');
            }
            if (data.hasOwnProperty('discount')) {
                obj['discount'] = ApiClient.convertToType(data['discount'], 'Number');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('max_uses')) {
                obj['max_uses'] = ApiClient.convertToType(data['max_uses'], 'Number');
            }
            if (data.hasOwnProperty('expiration_date')) {
                obj['expiration_date'] = ApiClient.convertToType(data['expiration_date'], 'String');
            }
            if (data.hasOwnProperty('allowed_emails')) {
                obj['allowed_emails'] = ApiClient.convertToType(data['allowed_emails'], ['String']);
            }
            if (data.hasOwnProperty('products')) {
                obj['products'] = ApiClient.convertToType(data['products'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PutV1ShopsShopIdCouponsCouponIdUpdateRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PutV1ShopsShopIdCouponsCouponIdUpdateRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PutV1ShopsShopIdCouponsCouponIdUpdateRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['code'] && !(typeof data['code'] === 'string' || data['code'] instanceof String)) {
            throw new Error("Expected the field `code` to be a primitive type in the JSON string but got " + data['code']);
        }
        // ensure the json data is a string
        if (data['type'] && !(typeof data['type'] === 'string' || data['type'] instanceof String)) {
            throw new Error("Expected the field `type` to be a primitive type in the JSON string but got " + data['type']);
        }
        // ensure the json data is a string
        if (data['expiration_date'] && !(typeof data['expiration_date'] === 'string' || data['expiration_date'] instanceof String)) {
            throw new Error("Expected the field `expiration_date` to be a primitive type in the JSON string but got " + data['expiration_date']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['allowed_emails'])) {
            throw new Error("Expected the field `allowed_emails` to be an array in the JSON data but got " + data['allowed_emails']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['products'])) {
            throw new Error("Expected the field `products` to be an array in the JSON data but got " + data['products']);
        }

        return true;
    }


}

PutV1ShopsShopIdCouponsCouponIdUpdateRequest.RequiredProperties = ["code", "global", "discount", "type"];

/**
 * 
 * @member {String} code
 */
PutV1ShopsShopIdCouponsCouponIdUpdateRequest.prototype['code'] = undefined;

/**
 * 
 * @member {Boolean} global
 */
PutV1ShopsShopIdCouponsCouponIdUpdateRequest.prototype['global'] = undefined;

/**
 * 
 * @member {Number} discount
 */
PutV1ShopsShopIdCouponsCouponIdUpdateRequest.prototype['discount'] = undefined;

/**
 * 
 * @member {module:model/PutV1ShopsShopIdCouponsCouponIdUpdateRequest.TypeEnum} type
 */
PutV1ShopsShopIdCouponsCouponIdUpdateRequest.prototype['type'] = undefined;

/**
 * 
 * @member {Number} max_uses
 */
PutV1ShopsShopIdCouponsCouponIdUpdateRequest.prototype['max_uses'] = undefined;

/**
 * Must be a valid date.
 * @member {String} expiration_date
 */
PutV1ShopsShopIdCouponsCouponIdUpdateRequest.prototype['expiration_date'] = undefined;

/**
 * Must be a valid email address.
 * @member {Array.<String>} allowed_emails
 */
PutV1ShopsShopIdCouponsCouponIdUpdateRequest.prototype['allowed_emails'] = undefined;

/**
 * 
 * @member {Array.<String>} products
 */
PutV1ShopsShopIdCouponsCouponIdUpdateRequest.prototype['products'] = undefined;





/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
PutV1ShopsShopIdCouponsCouponIdUpdateRequest['TypeEnum'] = {

    /**
     * value: "percentage"
     * @const
     */
    "percentage": "percentage",

    /**
     * value: "fixed"
     * @const
     */
    "fixed": "fixed"
};



export default PutV1ShopsShopIdCouponsCouponIdUpdateRequest;

