/**
 * SellAuth
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PutV1ShopsShopIdThemesThemeIdRequest model module.
 * @module model/PutV1ShopsShopIdThemesThemeIdRequest
 * @version 1.0.0
 */
class PutV1ShopsShopIdThemesThemeIdRequest {
    /**
     * Constructs a new <code>PutV1ShopsShopIdThemesThemeIdRequest</code>.
     * @alias module:model/PutV1ShopsShopIdThemesThemeIdRequest
     */
    constructor() { 
        
        PutV1ShopsShopIdThemesThemeIdRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PutV1ShopsShopIdThemesThemeIdRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PutV1ShopsShopIdThemesThemeIdRequest} obj Optional instance to populate.
     * @return {module:model/PutV1ShopsShopIdThemesThemeIdRequest} The populated <code>PutV1ShopsShopIdThemesThemeIdRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PutV1ShopsShopIdThemesThemeIdRequest();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('image_id')) {
                obj['image_id'] = ApiClient.convertToType(data['image_id'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PutV1ShopsShopIdThemesThemeIdRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PutV1ShopsShopIdThemesThemeIdRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['type'] && !(typeof data['type'] === 'string' || data['type'] instanceof String)) {
            throw new Error("Expected the field `type` to be a primitive type in the JSON string but got " + data['type']);
        }
        // ensure the json data is a string
        if (data['image_id'] && !(typeof data['image_id'] === 'string' || data['image_id'] instanceof String)) {
            throw new Error("Expected the field `image_id` to be a primitive type in the JSON string but got " + data['image_id']);
        }

        return true;
    }


}



/**
 * 
 * @member {String} name
 */
PutV1ShopsShopIdThemesThemeIdRequest.prototype['name'] = undefined;

/**
 * 
 * @member {String} description
 */
PutV1ShopsShopIdThemesThemeIdRequest.prototype['description'] = undefined;

/**
 * 
 * @member {module:model/PutV1ShopsShopIdThemesThemeIdRequest.TypeEnum} type
 */
PutV1ShopsShopIdThemesThemeIdRequest.prototype['type'] = undefined;

/**
 * 
 * @member {String} image_id
 */
PutV1ShopsShopIdThemesThemeIdRequest.prototype['image_id'] = undefined;





/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
PutV1ShopsShopIdThemesThemeIdRequest['TypeEnum'] = {

    /**
     * value: "private"
     * @const
     */
    "private": "private",

    /**
     * value: "public"
     * @const
     */
    "public": "public"
};



export default PutV1ShopsShopIdThemesThemeIdRequest;

