/**
 * SellAuth
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ThemeOfficialTheme from './ThemeOfficialTheme';

/**
 * The Theme model module.
 * @module model/Theme
 * @version 1.0.0
 */
class Theme {
    /**
     * Constructs a new <code>Theme</code>.
     * @alias module:model/Theme
     */
    constructor() { 
        
        Theme.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Theme</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Theme} obj Optional instance to populate.
     * @return {module:model/Theme} The populated <code>Theme</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Theme();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('version')) {
                obj['version'] = ApiClient.convertToType(data['version'], 'String');
            }
            if (data.hasOwnProperty('official_theme')) {
                obj['official_theme'] = ThemeOfficialTheme.constructFromObject(data['official_theme']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Theme</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Theme</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['version'] && !(typeof data['version'] === 'string' || data['version'] instanceof String)) {
            throw new Error("Expected the field `version` to be a primitive type in the JSON string but got " + data['version']);
        }
        // validate the optional field `official_theme`
        if (data['official_theme']) { // data not null
          ThemeOfficialTheme.validateJSON(data['official_theme']);
        }

        return true;
    }


}



/**
 * @member {Number} id
 */
Theme.prototype['id'] = undefined;

/**
 * @member {String} name
 */
Theme.prototype['name'] = undefined;

/**
 * @member {String} description
 */
Theme.prototype['description'] = undefined;

/**
 * @member {String} version
 */
Theme.prototype['version'] = undefined;

/**
 * @member {module:model/ThemeOfficialTheme} official_theme
 */
Theme.prototype['official_theme'] = undefined;






export default Theme;

