/**
 * SellAuth
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SellAuth);
  }
}(this, function(expect, SellAuth) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SellAuth.GetV1ShopsShopIdInvoicesInvoiceId200Response();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('GetV1ShopsShopIdInvoicesInvoiceId200Response', function() {
    it('should create an instance of GetV1ShopsShopIdInvoicesInvoiceId200Response', function() {
      // uncomment below and update the code to test GetV1ShopsShopIdInvoicesInvoiceId200Response
      //var instance = new SellAuth.GetV1ShopsShopIdInvoicesInvoiceId200Response();
      //expect(instance).to.be.a(SellAuth.GetV1ShopsShopIdInvoicesInvoiceId200Response);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new SellAuth.GetV1ShopsShopIdInvoicesInvoiceId200Response();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instance = new SellAuth.GetV1ShopsShopIdInvoicesInvoiceId200Response();
      //expect(instance).to.be();
    });

    it('should have the property productId (base name: "product_id")', function() {
      // uncomment below and update the code to test the property productId
      //var instance = new SellAuth.GetV1ShopsShopIdInvoicesInvoiceId200Response();
      //expect(instance).to.be();
    });

    it('should have the property variantId (base name: "variant_id")', function() {
      // uncomment below and update the code to test the property variantId
      //var instance = new SellAuth.GetV1ShopsShopIdInvoicesInvoiceId200Response();
      //expect(instance).to.be();
    });

    it('should have the property price (base name: "price")', function() {
      // uncomment below and update the code to test the property price
      //var instance = new SellAuth.GetV1ShopsShopIdInvoicesInvoiceId200Response();
      //expect(instance).to.be();
    });

    it('should have the property currency (base name: "currency")', function() {
      // uncomment below and update the code to test the property currency
      //var instance = new SellAuth.GetV1ShopsShopIdInvoicesInvoiceId200Response();
      //expect(instance).to.be();
    });

    it('should have the property gateway (base name: "gateway")', function() {
      // uncomment below and update the code to test the property gateway
      //var instance = new SellAuth.GetV1ShopsShopIdInvoicesInvoiceId200Response();
      //expect(instance).to.be();
    });

    it('should have the property email (base name: "email")', function() {
      // uncomment below and update the code to test the property email
      //var instance = new SellAuth.GetV1ShopsShopIdInvoicesInvoiceId200Response();
      //expect(instance).to.be();
    });

    it('should have the property salt (base name: "salt")', function() {
      // uncomment below and update the code to test the property salt
      //var instance = new SellAuth.GetV1ShopsShopIdInvoicesInvoiceId200Response();
      //expect(instance).to.be();
    });

    it('should have the property manual (base name: "manual")', function() {
      // uncomment below and update the code to test the property manual
      //var instance = new SellAuth.GetV1ShopsShopIdInvoicesInvoiceId200Response();
      //expect(instance).to.be();
    });

    it('should have the property createdAt (base name: "created_at")', function() {
      // uncomment below and update the code to test the property createdAt
      //var instance = new SellAuth.GetV1ShopsShopIdInvoicesInvoiceId200Response();
      //expect(instance).to.be();
    });

    it('should have the property completedAt (base name: "completed_at")', function() {
      // uncomment below and update the code to test the property completedAt
      //var instance = new SellAuth.GetV1ShopsShopIdInvoicesInvoiceId200Response();
      //expect(instance).to.be();
    });

    it('should have the property archived (base name: "archived")', function() {
      // uncomment below and update the code to test the property archived
      //var instance = new SellAuth.GetV1ShopsShopIdInvoicesInvoiceId200Response();
      //expect(instance).to.be();
    });

    it('should have the property uniqueId (base name: "unique_id")', function() {
      // uncomment below and update the code to test the property uniqueId
      //var instance = new SellAuth.GetV1ShopsShopIdInvoicesInvoiceId200Response();
      //expect(instance).to.be();
    });

    it('should have the property product (base name: "product")', function() {
      // uncomment below and update the code to test the property product
      //var instance = new SellAuth.GetV1ShopsShopIdInvoicesInvoiceId200Response();
      //expect(instance).to.be();
    });

    it('should have the property variant (base name: "variant")', function() {
      // uncomment below and update the code to test the property variant
      //var instance = new SellAuth.GetV1ShopsShopIdInvoicesInvoiceId200Response();
      //expect(instance).to.be();
    });

    it('should have the property couponId (base name: "coupon_id")', function() {
      // uncomment below and update the code to test the property couponId
      //var instance = new SellAuth.GetV1ShopsShopIdInvoicesInvoiceId200Response();
      //expect(instance).to.be();
    });

    it('should have the property paypalffEmail (base name: "paypalff_email")', function() {
      // uncomment below and update the code to test the property paypalffEmail
      //var instance = new SellAuth.GetV1ShopsShopIdInvoicesInvoiceId200Response();
      //expect(instance).to.be();
    });

    it('should have the property customerId (base name: "customer_id")', function() {
      // uncomment below and update the code to test the property customerId
      //var instance = new SellAuth.GetV1ShopsShopIdInvoicesInvoiceId200Response();
      //expect(instance).to.be();
    });

    it('should have the property delivered (base name: "delivered")', function() {
      // uncomment below and update the code to test the property delivered
      //var instance = new SellAuth.GetV1ShopsShopIdInvoicesInvoiceId200Response();
      //expect(instance).to.be();
    });

    it('should have the property amount (base name: "amount")', function() {
      // uncomment below and update the code to test the property amount
      //var instance = new SellAuth.GetV1ShopsShopIdInvoicesInvoiceId200Response();
      //expect(instance).to.be();
    });

    it('should have the property priceUsd (base name: "price_usd")', function() {
      // uncomment below and update the code to test the property priceUsd
      //var instance = new SellAuth.GetV1ShopsShopIdInvoicesInvoiceId200Response();
      //expect(instance).to.be();
    });

    it('should have the property customFields (base name: "custom_fields")', function() {
      // uncomment below and update the code to test the property customFields
      //var instance = new SellAuth.GetV1ShopsShopIdInvoicesInvoiceId200Response();
      //expect(instance).to.be();
    });

    it('should have the property ip (base name: "ip")', function() {
      // uncomment below and update the code to test the property ip
      //var instance = new SellAuth.GetV1ShopsShopIdInvoicesInvoiceId200Response();
      //expect(instance).to.be();
    });

    it('should have the property userAgent (base name: "user_agent")', function() {
      // uncomment below and update the code to test the property userAgent
      //var instance = new SellAuth.GetV1ShopsShopIdInvoicesInvoiceId200Response();
      //expect(instance).to.be();
    });

    it('should have the property cryptoAddress (base name: "crypto_address")', function() {
      // uncomment below and update the code to test the property cryptoAddress
      //var instance = new SellAuth.GetV1ShopsShopIdInvoicesInvoiceId200Response();
      //expect(instance).to.be();
    });

    it('should have the property cryptoAmount (base name: "crypto_amount")', function() {
      // uncomment below and update the code to test the property cryptoAmount
      //var instance = new SellAuth.GetV1ShopsShopIdInvoicesInvoiceId200Response();
      //expect(instance).to.be();
    });

    it('should have the property shopId (base name: "shop_id")', function() {
      // uncomment below and update the code to test the property shopId
      //var instance = new SellAuth.GetV1ShopsShopIdInvoicesInvoiceId200Response();
      //expect(instance).to.be();
    });

    it('should have the property cashappCashtag (base name: "cashapp_cashtag")', function() {
      // uncomment below and update the code to test the property cashappCashtag
      //var instance = new SellAuth.GetV1ShopsShopIdInvoicesInvoiceId200Response();
      //expect(instance).to.be();
    });

    it('should have the property venmoTag (base name: "venmo_tag")', function() {
      // uncomment below and update the code to test the property venmoTag
      //var instance = new SellAuth.GetV1ShopsShopIdInvoicesInvoiceId200Response();
      //expect(instance).to.be();
    });

    it('should have the property cashappReceiptId (base name: "cashapp_receipt_id")', function() {
      // uncomment below and update the code to test the property cashappReceiptId
      //var instance = new SellAuth.GetV1ShopsShopIdInvoicesInvoiceId200Response();
      //expect(instance).to.be();
    });

    it('should have the property cashappTransactionId (base name: "cashapp_transaction_id")', function() {
      // uncomment below and update the code to test the property cashappTransactionId
      //var instance = new SellAuth.GetV1ShopsShopIdInvoicesInvoiceId200Response();
      //expect(instance).to.be();
    });

    it('should have the property discordUserId (base name: "discord_user_id")', function() {
      // uncomment below and update the code to test the property discordUserId
      //var instance = new SellAuth.GetV1ShopsShopIdInvoicesInvoiceId200Response();
      //expect(instance).to.be();
    });

    it('should have the property paypalffTransactionId (base name: "paypalff_transaction_id")', function() {
      // uncomment below and update the code to test the property paypalffTransactionId
      //var instance = new SellAuth.GetV1ShopsShopIdInvoicesInvoiceId200Response();
      //expect(instance).to.be();
    });

    it('should have the property priceEur (base name: "price_eur")', function() {
      // uncomment below and update the code to test the property priceEur
      //var instance = new SellAuth.GetV1ShopsShopIdInvoicesInvoiceId200Response();
      //expect(instance).to.be();
    });

    it('should have the property paypalffCurrency (base name: "paypalff_currency")', function() {
      // uncomment below and update the code to test the property paypalffCurrency
      //var instance = new SellAuth.GetV1ShopsShopIdInvoicesInvoiceId200Response();
      //expect(instance).to.be();
    });

    it('should have the property paypalffNote (base name: "paypalff_note")', function() {
      // uncomment below and update the code to test the property paypalffNote
      //var instance = new SellAuth.GetV1ShopsShopIdInvoicesInvoiceId200Response();
      //expect(instance).to.be();
    });

    it('should have the property stripePiId (base name: "stripe_pi_id")', function() {
      // uncomment below and update the code to test the property stripePiId
      //var instance = new SellAuth.GetV1ShopsShopIdInvoicesInvoiceId200Response();
      //expect(instance).to.be();
    });

  });

}));
