/**
 * SellAuth
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SellAuth);
  }
}(this, function(expect, SellAuth) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SellAuth.GetV1ShopsShopIdProducts200ResponseDataInner();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('GetV1ShopsShopIdProducts200ResponseDataInner', function() {
    it('should create an instance of GetV1ShopsShopIdProducts200ResponseDataInner', function() {
      // uncomment below and update the code to test GetV1ShopsShopIdProducts200ResponseDataInner
      //var instance = new SellAuth.GetV1ShopsShopIdProducts200ResponseDataInner();
      //expect(instance).to.be.a(SellAuth.GetV1ShopsShopIdProducts200ResponseDataInner);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new SellAuth.GetV1ShopsShopIdProducts200ResponseDataInner();
      //expect(instance).to.be();
    });

    it('should have the property salt (base name: "salt")', function() {
      // uncomment below and update the code to test the property salt
      //var instance = new SellAuth.GetV1ShopsShopIdProducts200ResponseDataInner();
      //expect(instance).to.be();
    });

    it('should have the property path (base name: "path")', function() {
      // uncomment below and update the code to test the property path
      //var instance = new SellAuth.GetV1ShopsShopIdProducts200ResponseDataInner();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new SellAuth.GetV1ShopsShopIdProducts200ResponseDataInner();
      //expect(instance).to.be();
    });

    it('should have the property price (base name: "price")', function() {
      // uncomment below and update the code to test the property price
      //var instance = new SellAuth.GetV1ShopsShopIdProducts200ResponseDataInner();
      //expect(instance).to.be();
    });

    it('should have the property currency (base name: "currency")', function() {
      // uncomment below and update the code to test the property currency
      //var instance = new SellAuth.GetV1ShopsShopIdProducts200ResponseDataInner();
      //expect(instance).to.be();
    });

    it('should have the property deliverablesType (base name: "deliverables_type")', function() {
      // uncomment below and update the code to test the property deliverablesType
      //var instance = new SellAuth.GetV1ShopsShopIdProducts200ResponseDataInner();
      //expect(instance).to.be();
    });

    it('should have the property stock (base name: "stock")', function() {
      // uncomment below and update the code to test the property stock
      //var instance = new SellAuth.GetV1ShopsShopIdProducts200ResponseDataInner();
      //expect(instance).to.be();
    });

    it('should have the property groupId (base name: "group_id")', function() {
      // uncomment below and update the code to test the property groupId
      //var instance = new SellAuth.GetV1ShopsShopIdProducts200ResponseDataInner();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instance = new SellAuth.GetV1ShopsShopIdProducts200ResponseDataInner();
      //expect(instance).to.be();
    });

    it('should have the property visibility (base name: "visibility")', function() {
      // uncomment below and update the code to test the property visibility
      //var instance = new SellAuth.GetV1ShopsShopIdProducts200ResponseDataInner();
      //expect(instance).to.be();
    });

    it('should have the property stockCount (base name: "stock_count")', function() {
      // uncomment below and update the code to test the property stockCount
      //var instance = new SellAuth.GetV1ShopsShopIdProducts200ResponseDataInner();
      //expect(instance).to.be();
    });

    it('should have the property group (base name: "group")', function() {
      // uncomment below and update the code to test the property group
      //var instance = new SellAuth.GetV1ShopsShopIdProducts200ResponseDataInner();
      //expect(instance).to.be();
    });

  });

}));
