/**
 * SellAuth
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SellAuth);
  }
}(this, function(expect, SellAuth) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SellAuth.PostV1ShopsCreate200Response();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PostV1ShopsCreate200Response', function() {
    it('should create an instance of PostV1ShopsCreate200Response', function() {
      // uncomment below and update the code to test PostV1ShopsCreate200Response
      //var instance = new SellAuth.PostV1ShopsCreate200Response();
      //expect(instance).to.be.a(SellAuth.PostV1ShopsCreate200Response);
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new SellAuth.PostV1ShopsCreate200Response();
      //expect(instance).to.be();
    });

    it('should have the property subdomain (base name: "subdomain")', function() {
      // uncomment below and update the code to test the property subdomain
      //var instance = new SellAuth.PostV1ShopsCreate200Response();
      //expect(instance).to.be();
    });

    it('should have the property ownerId (base name: "owner_id")', function() {
      // uncomment below and update the code to test the property ownerId
      //var instance = new SellAuth.PostV1ShopsCreate200Response();
      //expect(instance).to.be();
    });

    it('should have the property updatedAt (base name: "updated_at")', function() {
      // uncomment below and update the code to test the property updatedAt
      //var instance = new SellAuth.PostV1ShopsCreate200Response();
      //expect(instance).to.be();
    });

    it('should have the property createdAt (base name: "created_at")', function() {
      // uncomment below and update the code to test the property createdAt
      //var instance = new SellAuth.PostV1ShopsCreate200Response();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new SellAuth.PostV1ShopsCreate200Response();
      //expect(instance).to.be();
    });

    it('should have the property isSubscribed (base name: "is_subscribed")', function() {
      // uncomment below and update the code to test the property isSubscribed
      //var instance = new SellAuth.PostV1ShopsCreate200Response();
      //expect(instance).to.be();
    });

    it('should have the property url (base name: "url")', function() {
      // uncomment below and update the code to test the property url
      //var instance = new SellAuth.PostV1ShopsCreate200Response();
      //expect(instance).to.be();
    });

    it('should have the property validPaymentMethods (base name: "valid_payment_methods")', function() {
      // uncomment below and update the code to test the property validPaymentMethods
      //var instance = new SellAuth.PostV1ShopsCreate200Response();
      //expect(instance).to.be();
    });

  });

}));
