/**
 * SellAuth
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SellAuth);
  }
}(this, function(expect, SellAuth) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SellAuth.PutV1ShopsShopIdProductsProductIdUpdateRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PutV1ShopsShopIdProductsProductIdUpdateRequest', function() {
    it('should create an instance of PutV1ShopsShopIdProductsProductIdUpdateRequest', function() {
      // uncomment below and update the code to test PutV1ShopsShopIdProductsProductIdUpdateRequest
      //var instance = new SellAuth.PutV1ShopsShopIdProductsProductIdUpdateRequest();
      //expect(instance).to.be.a(SellAuth.PutV1ShopsShopIdProductsProductIdUpdateRequest);
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new SellAuth.PutV1ShopsShopIdProductsProductIdUpdateRequest();
      //expect(instance).to.be();
    });

    it('should have the property path (base name: "path")', function() {
      // uncomment below and update the code to test the property path
      //var instance = new SellAuth.PutV1ShopsShopIdProductsProductIdUpdateRequest();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instance = new SellAuth.PutV1ShopsShopIdProductsProductIdUpdateRequest();
      //expect(instance).to.be();
    });

    it('should have the property instructions (base name: "instructions")', function() {
      // uncomment below and update the code to test the property instructions
      //var instance = new SellAuth.PutV1ShopsShopIdProductsProductIdUpdateRequest();
      //expect(instance).to.be();
    });

    it('should have the property outOfStockMessage (base name: "out_of_stock_message")', function() {
      // uncomment below and update the code to test the property outOfStockMessage
      //var instance = new SellAuth.PutV1ShopsShopIdProductsProductIdUpdateRequest();
      //expect(instance).to.be();
    });

    it('should have the property currency (base name: "currency")', function() {
      // uncomment below and update the code to test the property currency
      //var instance = new SellAuth.PutV1ShopsShopIdProductsProductIdUpdateRequest();
      //expect(instance).to.be();
    });

    it('should have the property deliverables (base name: "deliverables")', function() {
      // uncomment below and update the code to test the property deliverables
      //var instance = new SellAuth.PutV1ShopsShopIdProductsProductIdUpdateRequest();
      //expect(instance).to.be();
    });

    it('should have the property deliverablesType (base name: "deliverables_type")', function() {
      // uncomment below and update the code to test the property deliverablesType
      //var instance = new SellAuth.PutV1ShopsShopIdProductsProductIdUpdateRequest();
      //expect(instance).to.be();
    });

    it('should have the property stock (base name: "stock")', function() {
      // uncomment below and update the code to test the property stock
      //var instance = new SellAuth.PutV1ShopsShopIdProductsProductIdUpdateRequest();
      //expect(instance).to.be();
    });

    it('should have the property groupId (base name: "group_id")', function() {
      // uncomment below and update the code to test the property groupId
      //var instance = new SellAuth.PutV1ShopsShopIdProductsProductIdUpdateRequest();
      //expect(instance).to.be();
    });

    it('should have the property imageIds (base name: "image_ids")', function() {
      // uncomment below and update the code to test the property imageIds
      //var instance = new SellAuth.PutV1ShopsShopIdProductsProductIdUpdateRequest();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instance = new SellAuth.PutV1ShopsShopIdProductsProductIdUpdateRequest();
      //expect(instance).to.be();
    });

    it('should have the property visibility (base name: "visibility")', function() {
      // uncomment below and update the code to test the property visibility
      //var instance = new SellAuth.PutV1ShopsShopIdProductsProductIdUpdateRequest();
      //expect(instance).to.be();
    });

    it('should have the property paymentMethods (base name: "payment_methods")', function() {
      // uncomment below and update the code to test the property paymentMethods
      //var instance = new SellAuth.PutV1ShopsShopIdProductsProductIdUpdateRequest();
      //expect(instance).to.be();
    });

    it('should have the property price (base name: "price")', function() {
      // uncomment below and update the code to test the property price
      //var instance = new SellAuth.PutV1ShopsShopIdProductsProductIdUpdateRequest();
      //expect(instance).to.be();
    });

    it('should have the property quantityMin (base name: "quantity_min")', function() {
      // uncomment below and update the code to test the property quantityMin
      //var instance = new SellAuth.PutV1ShopsShopIdProductsProductIdUpdateRequest();
      //expect(instance).to.be();
    });

    it('should have the property quantityMax (base name: "quantity_max")', function() {
      // uncomment below and update the code to test the property quantityMax
      //var instance = new SellAuth.PutV1ShopsShopIdProductsProductIdUpdateRequest();
      //expect(instance).to.be();
    });

    it('should have the property volumeDiscounts (base name: "volume_discounts")', function() {
      // uncomment below and update the code to test the property volumeDiscounts
      //var instance = new SellAuth.PutV1ShopsShopIdProductsProductIdUpdateRequest();
      //expect(instance).to.be();
    });

    it('should have the property discordGuildId (base name: "discord_guild_id")', function() {
      // uncomment below and update the code to test the property discordGuildId
      //var instance = new SellAuth.PutV1ShopsShopIdProductsProductIdUpdateRequest();
      //expect(instance).to.be();
    });

    it('should have the property discordRoleId (base name: "discord_role_id")', function() {
      // uncomment below and update the code to test the property discordRoleId
      //var instance = new SellAuth.PutV1ShopsShopIdProductsProductIdUpdateRequest();
      //expect(instance).to.be();
    });

    it('should have the property blockVpn (base name: "block_vpn")', function() {
      // uncomment below and update the code to test the property blockVpn
      //var instance = new SellAuth.PutV1ShopsShopIdProductsProductIdUpdateRequest();
      //expect(instance).to.be();
    });

    it('should have the property customFieldIds (base name: "custom_field_ids")', function() {
      // uncomment below and update the code to test the property customFieldIds
      //var instance = new SellAuth.PutV1ShopsShopIdProductsProductIdUpdateRequest();
      //expect(instance).to.be();
    });

    it('should have the property variants (base name: "variants")', function() {
      // uncomment below and update the code to test the property variants
      //var instance = new SellAuth.PutV1ShopsShopIdProductsProductIdUpdateRequest();
      //expect(instance).to.be();
    });

  });

}));
