/**
 * SellAuth
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SellAuth);
  }
}(this, function(expect, SellAuth) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SellAuth.Shop();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Shop', function() {
    it('should create an instance of Shop', function() {
      // uncomment below and update the code to test Shop
      //var instance = new SellAuth.Shop();
      //expect(instance).to.be.a(SellAuth.Shop);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new SellAuth.Shop();
      //expect(instance).to.be();
    });

    it('should have the property createdAt (base name: "created_at")', function() {
      // uncomment below and update the code to test the property createdAt
      //var instance = new SellAuth.Shop();
      //expect(instance).to.be();
    });

    it('should have the property updatedAt (base name: "updated_at")', function() {
      // uncomment below and update the code to test the property updatedAt
      //var instance = new SellAuth.Shop();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new SellAuth.Shop();
      //expect(instance).to.be();
    });

    it('should have the property subdomain (base name: "subdomain")', function() {
      // uncomment below and update the code to test the property subdomain
      //var instance = new SellAuth.Shop();
      //expect(instance).to.be();
    });

    it('should have the property logoImageId (base name: "logo_image_id")', function() {
      // uncomment below and update the code to test the property logoImageId
      //var instance = new SellAuth.Shop();
      //expect(instance).to.be();
    });

    it('should have the property faviconImageId (base name: "favicon_image_id")', function() {
      // uncomment below and update the code to test the property faviconImageId
      //var instance = new SellAuth.Shop();
      //expect(instance).to.be();
    });

    it('should have the property backgroundImageId (base name: "background_image_id")', function() {
      // uncomment below and update the code to test the property backgroundImageId
      //var instance = new SellAuth.Shop();
      //expect(instance).to.be();
    });

    it('should have the property imageUrl (base name: "image_url")', function() {
      // uncomment below and update the code to test the property imageUrl
      //var instance = new SellAuth.Shop();
      //expect(instance).to.be();
    });

    it('should have the property backgroundImageUrl (base name: "background_image_url")', function() {
      // uncomment below and update the code to test the property backgroundImageUrl
      //var instance = new SellAuth.Shop();
      //expect(instance).to.be();
    });

    it('should have the property bitcoinAddress (base name: "bitcoin_address")', function() {
      // uncomment below and update the code to test the property bitcoinAddress
      //var instance = new SellAuth.Shop();
      //expect(instance).to.be();
    });

    it('should have the property bitcoinWallet (base name: "bitcoin_wallet")', function() {
      // uncomment below and update the code to test the property bitcoinWallet
      //var instance = new SellAuth.Shop();
      //expect(instance).to.be();
    });

    it('should have the property litecoinAddress (base name: "litecoin_address")', function() {
      // uncomment below and update the code to test the property litecoinAddress
      //var instance = new SellAuth.Shop();
      //expect(instance).to.be();
    });

    it('should have the property litecoinWallet (base name: "litecoin_wallet")', function() {
      // uncomment below and update the code to test the property litecoinWallet
      //var instance = new SellAuth.Shop();
      //expect(instance).to.be();
    });

    it('should have the property paypalEmail (base name: "paypal_email")', function() {
      // uncomment below and update the code to test the property paypalEmail
      //var instance = new SellAuth.Shop();
      //expect(instance).to.be();
    });

    it('should have the property paypalMethod (base name: "paypal_method")', function() {
      // uncomment below and update the code to test the property paypalMethod
      //var instance = new SellAuth.Shop();
      //expect(instance).to.be();
    });

    it('should have the property paypalClientId (base name: "paypal_client_id")', function() {
      // uncomment below and update the code to test the property paypalClientId
      //var instance = new SellAuth.Shop();
      //expect(instance).to.be();
    });

    it('should have the property paypalClientSecret (base name: "paypal_client_secret")', function() {
      // uncomment below and update the code to test the property paypalClientSecret
      //var instance = new SellAuth.Shop();
      //expect(instance).to.be();
    });

    it('should have the property paypalWebhookId (base name: "paypal_webhook_id")', function() {
      // uncomment below and update the code to test the property paypalWebhookId
      //var instance = new SellAuth.Shop();
      //expect(instance).to.be();
    });

    it('should have the property paypalffMethod (base name: "paypalff_method")', function() {
      // uncomment below and update the code to test the property paypalffMethod
      //var instance = new SellAuth.Shop();
      //expect(instance).to.be();
    });

    it('should have the property stripeApiKey (base name: "stripe_api_key")', function() {
      // uncomment below and update the code to test the property stripeApiKey
      //var instance = new SellAuth.Shop();
      //expect(instance).to.be();
    });

    it('should have the property stripeWebhookSecret (base name: "stripe_webhook_secret")', function() {
      // uncomment below and update the code to test the property stripeWebhookSecret
      //var instance = new SellAuth.Shop();
      //expect(instance).to.be();
    });

    it('should have the property ownerId (base name: "owner_id")', function() {
      // uncomment below and update the code to test the property ownerId
      //var instance = new SellAuth.Shop();
      //expect(instance).to.be();
    });

    it('should have the property cashappCashtag (base name: "cashapp_cashtag")', function() {
      // uncomment below and update the code to test the property cashappCashtag
      //var instance = new SellAuth.Shop();
      //expect(instance).to.be();
    });

    it('should have the property cashappEmail (base name: "cashapp_email")', function() {
      // uncomment below and update the code to test the property cashappEmail
      //var instance = new SellAuth.Shop();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instance = new SellAuth.Shop();
      //expect(instance).to.be();
    });

    it('should have the property validPaymentMethods (base name: "valid_payment_methods")', function() {
      // uncomment below and update the code to test the property validPaymentMethods
      //var instance = new SellAuth.Shop();
      //expect(instance).to.be();
    });

    it('should have the property theme (base name: "theme")', function() {
      // uncomment below and update the code to test the property theme
      //var instance = new SellAuth.Shop();
      //expect(instance).to.be();
    });

    it('should have the property isSubscribed (base name: "is_subscribed")', function() {
      // uncomment below and update the code to test the property isSubscribed
      //var instance = new SellAuth.Shop();
      //expect(instance).to.be();
    });

    it('should have the property subscriptionEndTime (base name: "subscription_end_time")', function() {
      // uncomment below and update the code to test the property subscriptionEndTime
      //var instance = new SellAuth.Shop();
      //expect(instance).to.be();
    });

  });

}));
