/**
 * SellAuth
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SellAuth);
  }
}(this, function(expect, SellAuth) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SellAuth.EndpointsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('EndpointsApi', function() {
    describe('deleteV1ShopsShopIdBlacklistBlacklistId', function() {
      it('should call deleteV1ShopsShopIdBlacklistBlacklistId successfully', function(done) {
        //uncomment below and update the code to test deleteV1ShopsShopIdBlacklistBlacklistId
        //instance.deleteV1ShopsShopIdBlacklistBlacklistId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteV1ShopsShopIdCouponsCouponId', function() {
      it('should call deleteV1ShopsShopIdCouponsCouponId successfully', function(done) {
        //uncomment below and update the code to test deleteV1ShopsShopIdCouponsCouponId
        //instance.deleteV1ShopsShopIdCouponsCouponId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteV1ShopsShopIdCustomFieldsCustomFieldId', function() {
      it('should call deleteV1ShopsShopIdCustomFieldsCustomFieldId successfully', function(done) {
        //uncomment below and update the code to test deleteV1ShopsShopIdCustomFieldsCustomFieldId
        //instance.deleteV1ShopsShopIdCustomFieldsCustomFieldId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteV1ShopsShopIdDomainsDomainId', function() {
      it('should call deleteV1ShopsShopIdDomainsDomainId successfully', function(done) {
        //uncomment below and update the code to test deleteV1ShopsShopIdDomainsDomainId
        //instance.deleteV1ShopsShopIdDomainsDomainId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteV1ShopsShopIdGroupsGroupId', function() {
      it('should call deleteV1ShopsShopIdGroupsGroupId successfully', function(done) {
        //uncomment below and update the code to test deleteV1ShopsShopIdGroupsGroupId
        //instance.deleteV1ShopsShopIdGroupsGroupId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteV1ShopsShopIdImagesImageId', function() {
      it('should call deleteV1ShopsShopIdImagesImageId successfully', function(done) {
        //uncomment below and update the code to test deleteV1ShopsShopIdImagesImageId
        //instance.deleteV1ShopsShopIdImagesImageId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteV1ShopsShopIdProductsProductId', function() {
      it('should call deleteV1ShopsShopIdProductsProductId successfully', function(done) {
        //uncomment below and update the code to test deleteV1ShopsShopIdProductsProductId
        //instance.deleteV1ShopsShopIdProductsProductId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteV1ShopsShopIdThemesThemeId', function() {
      it('should call deleteV1ShopsShopIdThemesThemeId successfully', function(done) {
        //uncomment below and update the code to test deleteV1ShopsShopIdThemesThemeId
        //instance.deleteV1ShopsShopIdThemesThemeId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getV1Shops', function() {
      it('should call getV1Shops successfully', function(done) {
        //uncomment below and update the code to test getV1Shops
        //instance.getV1Shops(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getV1ShopsShopId', function() {
      it('should call getV1ShopsShopId successfully', function(done) {
        //uncomment below and update the code to test getV1ShopsShopId
        //instance.getV1ShopsShopId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getV1ShopsShopIdBlacklist', function() {
      it('should call getV1ShopsShopIdBlacklist successfully', function(done) {
        //uncomment below and update the code to test getV1ShopsShopIdBlacklist
        //instance.getV1ShopsShopIdBlacklist(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getV1ShopsShopIdCoupons', function() {
      it('should call getV1ShopsShopIdCoupons successfully', function(done) {
        //uncomment below and update the code to test getV1ShopsShopIdCoupons
        //instance.getV1ShopsShopIdCoupons(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getV1ShopsShopIdCouponsCouponId', function() {
      it('should call getV1ShopsShopIdCouponsCouponId successfully', function(done) {
        //uncomment below and update the code to test getV1ShopsShopIdCouponsCouponId
        //instance.getV1ShopsShopIdCouponsCouponId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getV1ShopsShopIdCustomFields', function() {
      it('should call getV1ShopsShopIdCustomFields successfully', function(done) {
        //uncomment below and update the code to test getV1ShopsShopIdCustomFields
        //instance.getV1ShopsShopIdCustomFields(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getV1ShopsShopIdDomains', function() {
      it('should call getV1ShopsShopIdDomains successfully', function(done) {
        //uncomment below and update the code to test getV1ShopsShopIdDomains
        //instance.getV1ShopsShopIdDomains(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getV1ShopsShopIdDomainsDomainId', function() {
      it('should call getV1ShopsShopIdDomainsDomainId successfully', function(done) {
        //uncomment below and update the code to test getV1ShopsShopIdDomainsDomainId
        //instance.getV1ShopsShopIdDomainsDomainId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getV1ShopsShopIdFeedbacks', function() {
      it('should call getV1ShopsShopIdFeedbacks successfully', function(done) {
        //uncomment below and update the code to test getV1ShopsShopIdFeedbacks
        //instance.getV1ShopsShopIdFeedbacks(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getV1ShopsShopIdFeedbacksFeedbackId', function() {
      it('should call getV1ShopsShopIdFeedbacksFeedbackId successfully', function(done) {
        //uncomment below and update the code to test getV1ShopsShopIdFeedbacksFeedbackId
        //instance.getV1ShopsShopIdFeedbacksFeedbackId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getV1ShopsShopIdGroups', function() {
      it('should call getV1ShopsShopIdGroups successfully', function(done) {
        //uncomment below and update the code to test getV1ShopsShopIdGroups
        //instance.getV1ShopsShopIdGroups(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getV1ShopsShopIdGroupsGroupId', function() {
      it('should call getV1ShopsShopIdGroupsGroupId successfully', function(done) {
        //uncomment below and update the code to test getV1ShopsShopIdGroupsGroupId
        //instance.getV1ShopsShopIdGroupsGroupId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getV1ShopsShopIdImages', function() {
      it('should call getV1ShopsShopIdImages successfully', function(done) {
        //uncomment below and update the code to test getV1ShopsShopIdImages
        //instance.getV1ShopsShopIdImages(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getV1ShopsShopIdInvoices', function() {
      it('should call getV1ShopsShopIdInvoices successfully', function(done) {
        //uncomment below and update the code to test getV1ShopsShopIdInvoices
        //instance.getV1ShopsShopIdInvoices(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getV1ShopsShopIdInvoicesInvoiceId', function() {
      it('should call getV1ShopsShopIdInvoicesInvoiceId successfully', function(done) {
        //uncomment below and update the code to test getV1ShopsShopIdInvoicesInvoiceId
        //instance.getV1ShopsShopIdInvoicesInvoiceId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getV1ShopsShopIdInvoicesInvoiceIdProcess', function() {
      it('should call getV1ShopsShopIdInvoicesInvoiceIdProcess successfully', function(done) {
        //uncomment below and update the code to test getV1ShopsShopIdInvoicesInvoiceIdProcess
        //instance.getV1ShopsShopIdInvoicesInvoiceIdProcess(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getV1ShopsShopIdPayouts', function() {
      it('should call getV1ShopsShopIdPayouts successfully', function(done) {
        //uncomment below and update the code to test getV1ShopsShopIdPayouts
        //instance.getV1ShopsShopIdPayouts(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getV1ShopsShopIdPayoutsBalances', function() {
      it('should call getV1ShopsShopIdPayoutsBalances successfully', function(done) {
        //uncomment below and update the code to test getV1ShopsShopIdPayoutsBalances
        //instance.getV1ShopsShopIdPayoutsBalances(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getV1ShopsShopIdPayoutsTransactions', function() {
      it('should call getV1ShopsShopIdPayoutsTransactions successfully', function(done) {
        //uncomment below and update the code to test getV1ShopsShopIdPayoutsTransactions
        //instance.getV1ShopsShopIdPayoutsTransactions(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getV1ShopsShopIdProducts', function() {
      it('should call getV1ShopsShopIdProducts successfully', function(done) {
        //uncomment below and update the code to test getV1ShopsShopIdProducts
        //instance.getV1ShopsShopIdProducts(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getV1ShopsShopIdProductsProductId', function() {
      it('should call getV1ShopsShopIdProductsProductId successfully', function(done) {
        //uncomment below and update the code to test getV1ShopsShopIdProductsProductId
        //instance.getV1ShopsShopIdProductsProductId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getV1ShopsShopIdStats', function() {
      it('should call getV1ShopsShopIdStats successfully', function(done) {
        //uncomment below and update the code to test getV1ShopsShopIdStats
        //instance.getV1ShopsShopIdStats(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getV1ShopsShopIdThemes', function() {
      it('should call getV1ShopsShopIdThemes successfully', function(done) {
        //uncomment below and update the code to test getV1ShopsShopIdThemes
        //instance.getV1ShopsShopIdThemes(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getV1ShopsShopIdThemesThemeId', function() {
      it('should call getV1ShopsShopIdThemesThemeId successfully', function(done) {
        //uncomment below and update the code to test getV1ShopsShopIdThemesThemeId
        //instance.getV1ShopsShopIdThemesThemeId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postV1ShopsCreate', function() {
      it('should call postV1ShopsCreate successfully', function(done) {
        //uncomment below and update the code to test postV1ShopsCreate
        //instance.postV1ShopsCreate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postV1ShopsShopIdBlacklist', function() {
      it('should call postV1ShopsShopIdBlacklist successfully', function(done) {
        //uncomment below and update the code to test postV1ShopsShopIdBlacklist
        //instance.postV1ShopsShopIdBlacklist(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postV1ShopsShopIdCoupons', function() {
      it('should call postV1ShopsShopIdCoupons successfully', function(done) {
        //uncomment below and update the code to test postV1ShopsShopIdCoupons
        //instance.postV1ShopsShopIdCoupons(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postV1ShopsShopIdCustomFields', function() {
      it('should call postV1ShopsShopIdCustomFields successfully', function(done) {
        //uncomment below and update the code to test postV1ShopsShopIdCustomFields
        //instance.postV1ShopsShopIdCustomFields(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postV1ShopsShopIdDomains', function() {
      it('should call postV1ShopsShopIdDomains successfully', function(done) {
        //uncomment below and update the code to test postV1ShopsShopIdDomains
        //instance.postV1ShopsShopIdDomains(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postV1ShopsShopIdFeedbacksFeedbackIdAppeal', function() {
      it('should call postV1ShopsShopIdFeedbacksFeedbackIdAppeal successfully', function(done) {
        //uncomment below and update the code to test postV1ShopsShopIdFeedbacksFeedbackIdAppeal
        //instance.postV1ShopsShopIdFeedbacksFeedbackIdAppeal(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postV1ShopsShopIdFeedbacksFeedbackIdReply', function() {
      it('should call postV1ShopsShopIdFeedbacksFeedbackIdReply successfully', function(done) {
        //uncomment below and update the code to test postV1ShopsShopIdFeedbacksFeedbackIdReply
        //instance.postV1ShopsShopIdFeedbacksFeedbackIdReply(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postV1ShopsShopIdGroups', function() {
      it('should call postV1ShopsShopIdGroups successfully', function(done) {
        //uncomment below and update the code to test postV1ShopsShopIdGroups
        //instance.postV1ShopsShopIdGroups(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postV1ShopsShopIdImages', function() {
      it('should call postV1ShopsShopIdImages successfully', function(done) {
        //uncomment below and update the code to test postV1ShopsShopIdImages
        //instance.postV1ShopsShopIdImages(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postV1ShopsShopIdInvoicesInvoiceIdArchive', function() {
      it('should call postV1ShopsShopIdInvoicesInvoiceIdArchive successfully', function(done) {
        //uncomment below and update the code to test postV1ShopsShopIdInvoicesInvoiceIdArchive
        //instance.postV1ShopsShopIdInvoicesInvoiceIdArchive(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postV1ShopsShopIdInvoicesInvoiceIdUnarchive', function() {
      it('should call postV1ShopsShopIdInvoicesInvoiceIdUnarchive successfully', function(done) {
        //uncomment below and update the code to test postV1ShopsShopIdInvoicesInvoiceIdUnarchive
        //instance.postV1ShopsShopIdInvoicesInvoiceIdUnarchive(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postV1ShopsShopIdPayoutsPayout', function() {
      it('should call postV1ShopsShopIdPayoutsPayout successfully', function(done) {
        //uncomment below and update the code to test postV1ShopsShopIdPayoutsPayout
        //instance.postV1ShopsShopIdPayoutsPayout(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postV1ShopsShopIdProducts', function() {
      it('should call postV1ShopsShopIdProducts successfully', function(done) {
        //uncomment below and update the code to test postV1ShopsShopIdProducts
        //instance.postV1ShopsShopIdProducts(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postV1ShopsShopIdThemes', function() {
      it('should call postV1ShopsShopIdThemes successfully', function(done) {
        //uncomment below and update the code to test postV1ShopsShopIdThemes
        //instance.postV1ShopsShopIdThemes(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postV1ShopsShopIdThemesThemeIdImport', function() {
      it('should call postV1ShopsShopIdThemesThemeIdImport successfully', function(done) {
        //uncomment below and update the code to test postV1ShopsShopIdThemesThemeIdImport
        //instance.postV1ShopsShopIdThemesThemeIdImport(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postV1ShopsShopIdThemesThemeIdUpdate', function() {
      it('should call postV1ShopsShopIdThemesThemeIdUpdate successfully', function(done) {
        //uncomment below and update the code to test postV1ShopsShopIdThemesThemeIdUpdate
        //instance.postV1ShopsShopIdThemesThemeIdUpdate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putV1ShopsShopIdCouponsCouponIdUpdate', function() {
      it('should call putV1ShopsShopIdCouponsCouponIdUpdate successfully', function(done) {
        //uncomment below and update the code to test putV1ShopsShopIdCouponsCouponIdUpdate
        //instance.putV1ShopsShopIdCouponsCouponIdUpdate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putV1ShopsShopIdCustomFieldsCustomFieldId', function() {
      it('should call putV1ShopsShopIdCustomFieldsCustomFieldId successfully', function(done) {
        //uncomment below and update the code to test putV1ShopsShopIdCustomFieldsCustomFieldId
        //instance.putV1ShopsShopIdCustomFieldsCustomFieldId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putV1ShopsShopIdGroupsGroupIdUpdate', function() {
      it('should call putV1ShopsShopIdGroupsGroupIdUpdate successfully', function(done) {
        //uncomment below and update the code to test putV1ShopsShopIdGroupsGroupIdUpdate
        //instance.putV1ShopsShopIdGroupsGroupIdUpdate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putV1ShopsShopIdPaymentProcessorsUpdate', function() {
      it('should call putV1ShopsShopIdPaymentProcessorsUpdate successfully', function(done) {
        //uncomment below and update the code to test putV1ShopsShopIdPaymentProcessorsUpdate
        //instance.putV1ShopsShopIdPaymentProcessorsUpdate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putV1ShopsShopIdProductsProductIdUpdate', function() {
      it('should call putV1ShopsShopIdProductsProductIdUpdate successfully', function(done) {
        //uncomment below and update the code to test putV1ShopsShopIdProductsProductIdUpdate
        //instance.putV1ShopsShopIdProductsProductIdUpdate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putV1ShopsShopIdThemesThemeId', function() {
      it('should call putV1ShopsShopIdThemesThemeId successfully', function(done) {
        //uncomment below and update the code to test putV1ShopsShopIdThemesThemeId
        //instance.putV1ShopsShopIdThemesThemeId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putV1ShopsShopIdThemesThemeIdApply', function() {
      it('should call putV1ShopsShopIdThemesThemeIdApply successfully', function(done) {
        //uncomment below and update the code to test putV1ShopsShopIdThemesThemeIdApply
        //instance.putV1ShopsShopIdThemesThemeIdApply(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putV1ShopsShopIdUpdate', function() {
      it('should call putV1ShopsShopIdUpdate successfully', function(done) {
        //uncomment below and update the code to test putV1ShopsShopIdUpdate
        //instance.putV1ShopsShopIdUpdate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
